name: github-release

on:
  push:
    branches: [master]

jobs:
  github-release:
    timeout-minutes: 5

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-semantic-release@v2
